wget http://files.rcsb.org/download/1SCT.pdb -O pdb1sct.ent
wget http://files.rcsb.org/download/3CUM.pdb -O pdb3cum.ent
wget http://files.rcsb.org/download/2QAM.pdb -O pdb2qam.ent
wget http://files.rcsb.org/download/2GY9.pdb -O pdb2gy9.ent
wget http://files.rcsb.org/download/2GNR.pdb -O pdb2gnr.ent
wget http://files.rcsb.org/download/2J01.pdb -O pdb2j01.ent
wget http://files.rcsb.org/download/1WB1.pdb -O pdb1wb1.ent
wget http://files.rcsb.org/download/2I6C.pdb -O pdb2i6c.ent
wget http://files.rcsb.org/download/2H7M.pdb -O pdb2h7m.ent
wget http://files.rcsb.org/download/1ZX0.pdb -O pdb1zx0.ent
wget http://files.rcsb.org/download/1XM0.pdb -O pdb1xm0.ent
wget http://files.rcsb.org/download/1O0Y.pdb -O pdb1o0y.ent
wget http://files.rcsb.org/download/1VLF.pdb -O pdb1vlf.ent
wget http://files.rcsb.org/download/2FFE.pdb -O pdb2ffe.ent
wget http://files.rcsb.org/download/2DTG.pdb -O pdb2dtg.ent
wget http://files.rcsb.org/download/1UUL.pdb -O pdb1uul.ent
wget http://files.rcsb.org/download/2GJC.pdb -O pdb2gjc.ent
wget http://files.rcsb.org/download/3C7B.pdb -O pdb3c7b.ent
wget http://files.rcsb.org/download/1OJU.pdb -O pdb1oju.ent
wget http://files.rcsb.org/download/2IN1.pdb -O pdb2in1.ent
wget http://files.rcsb.org/download/2QAL.pdb -O pdb2qal.ent
wget http://files.rcsb.org/download/1WE3.pdb -O pdb1we3.ent
wget http://files.rcsb.org/download/2FB1.pdb -O pdb2fb1.ent
wget http://files.rcsb.org/download/1V7B.pdb -O pdb1v7b.ent
wget http://files.rcsb.org/download/2ALI.pdb -O pdb2ali.ent
wget http://files.rcsb.org/download/2FRN.pdb -O pdb2frn.ent
wget http://files.rcsb.org/download/1Q9R.pdb -O pdb1q9r.ent
wget http://files.rcsb.org/download/1CMW.pdb -O pdb1cmw.ent
wget http://files.rcsb.org/download/2GYC.pdb -O pdb2gyc.ent
wget http://files.rcsb.org/download/2OLR.pdb -O pdb2o1r.ent
wget http://files.rcsb.org/download/2A7V.pdb -O pdb2a7v.ent
wget http://files.rcsb.org/download/1ADT.pdb -O pdb1adt.ent
wget http://files.rcsb.org/download/1VJJ.pdb -O pdb1vjj.ent
